apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
    traefik.docker.network: cashmanager-net
    traefik.enable: "true"
    traefik.http.routers.api.entrypoints: websecure
    traefik.http.routers.api.rule: Host(``)&& PathPrefix(`/api`)
    traefik.http.routers.api.tls: "true"
    traefik.http.routers.api.tls.certresolver: traefik
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: api
    spec:
      containers:
      - image: api
        name: api
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
