apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: pgadmin
  name: pgadmin
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: pgadmin
    spec:
      containers:
      - env:
        - name: PGADMIN_CONFIG_SERVER_MODE
          value: "False"
        - name: PGADMIN_DEFAULT_EMAIL
        - name: PGADMIN_DEFAULT_PASSWORD
        image: dpage/pgadmin4
        name: pgadmin_container
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/pgadmin
          name: pgadmin
      restartPolicy: Always
      volumes:
      - name: pgadmin
        persistentVolumeClaim:
          claimName: pgadmin
status: {}
