apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: postgres
    spec:
      containers:
      - env:
        - name: PGDATA
          value: /data/postgres
        - name: POSTGRES_DB
        - name: POSTGRES_PASSWORD
        - name: POSTGRES_USER
        image: postgres
        name: postgres_container
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /data/postgres
          name: postgres
      restartPolicy: Always
      volumes:
      - name: postgres
        persistentVolumeClaim:
          claimName: postgres
status: {}
