apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
    traefik.enable: "true"
    traefik.http.routers.traefik.entrypoints: websecure
    traefik.http.routers.traefik.rule: Host(``)
    traefik.http.routers.traefik.tls: "true"
    traefik.http.routers.traefik.tls.certresolver: traefik
    traefik.http.services.traefik-service.loadbalancer.server.port: "8080"
  creationTimestamp: null
  labels:
    io.kompose.service: traefik
  name: traefik
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: traefik
    spec:
      containers:
      - args:
        - --log.level=DEBUG
        - --api
        - --metrics
        - --metrics.prometheus.buckets=0.1,0.3,1.2,5.0
        - --api.insecure=true
        - --providers.docker=true
        - --providers.docker.exposedbydefault=false
        - --entrypoints.web.address=:80
        - --entrypoints.websecure.address=:443
        - --certificatesresolvers.dnsresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
        - --certificatesresolvers.traefik.acme.email=
        - --certificatesresolvers.traefik.acme.storage=/letsencrypt/acme.json
        - --certificatesresolvers.traefik.acme.tlschallenge=true
        - --providers.file.filename=/run/traefik.toml
        image: traefik:v2.2
        name: traefik
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: traefik-claim0
          readOnly: true
        - mountPath: /letsencrypt
          name: traefik-claim1
        - mountPath: /run/traefik.toml
          name: traefik-claim2
      restartPolicy: Always
      volumes:
      - name: traefik-claim0
        persistentVolumeClaim:
          claimName: traefik-claim0
          readOnly: true
      - name: traefik-claim1
        persistentVolumeClaim:
          claimName: traefik-claim1
      - name: traefik-claim2
        persistentVolumeClaim:
          claimName: traefik-claim2
status: {}
