
server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: edu.epitech.bank_server.configuration.CustomPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/bank_server"
    username: postgres
    password: postgres