name: CI to Docker Hub
on:
  push:
    branches: [ main ]
    
jobs:
 build__push_back:
    runs-on: ubuntu-latest
    steps:
    
      - name: Check Out Repo API
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker 

      - name: Build and push bank_server
        id: docker_build_bank_server
        uses: docker/build-push-action@v2
        with:
          context: ./bank_server
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/bank_server-epitech:latest

      - name: Image digest bank_server
        run: echo ${{ steps.docker_build.outputs.digest }}
